#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts
flatpak run com.spotify.Client &
flatpak run com.discordapp.Discord &
slack &
# waybar
$scripts/launch_waybar &

# wallpaper set to cloud.png
swww init && swww img $HOME/.images/wall-gruv.png
# effects
#$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/libexec/xdg-desktop-portal &
