require('config.treesitter')
require('config.telescope')
require('config.cmp')
require('config.cmp-pandoc')
require('config.which-key')
require('config.galaxyline')
require('config.rainbow')
require('config.comment')
require('config.barbar')
require('config.autopairs')
require('config.nvimtree')
require('config.lspInstall')
require('config.autoSave')
require('config.dap')
require('config.dap-ui')
require('config.indentline')
require('config.presence')
require('config.clipboard-image')
require('config.pandoc')
-- require('config.signature')
-- require('config.colorizer')
